### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by whippingdot** [whippingdot/personal-website#3]
# My Ideas

- [ ] #4
- [ ] #5
- [ ] Create other pages
- [ ] #6
- [ ] #7
- [ ] Home page navbar
- [ ] Updating Profile Picture (using discord API maybe)
